### ISSUE TITLE
上手指南硬件引脚图问题

### ISSUE THREAD

**Issue by xuminglu1987** [ART-6LoWPAN/art-6lowpan#4]
外扩SPI：由下到上，E_CS-14-PA0   SPI2_SCK-34-PB13  SPI2_MOSI-36-PB15 SPI2_MISO-35-PB14

**Comment by armink** [comment]
![image](https://user-images.githubusercontent.com/1734686/33889246-80299eaa-df8a-11e7-8825-a890e390beb2.png)
这些都错了吗？

**Comment by xuminglu1987** [comment]
@armink是的

**Comment by armink** [comment]
fixed it on feb3627476f83f48dc0cd61aabe741af8fbddb6e
