### ISSUE TITLE
烧录脚本增加整片擦除功能

### ISSUE THREAD

**Issue by ShareCat** [ART-6LoWPAN/art-6lowpan#6]
si 1
exec device=stm32f405rg
speed auto
r
erase
r
h
loadbin ../bootloader.bin 0x08000000
loadbin ../application.bin 0x08010000
r
g
q

**Comment by armink** [comment]
之前一直在找类似命令，没有找到。多谢分享哈

**Comment by ShareCat** [comment]
我也是看到README.md里面提到没有整片擦除的功能，就到电脑安装的JLink驱动里面去找，找到JLink.exe这个可执行文件打开后，输入'?'回车，就有所有命令提示信息，找到擦除的命令 : )

本应该我修改后pull requsets的，但实在是git命令用的少，又有点懒...所以还是需要麻烦你来整合~

**Comment by ShareCat** [comment]
对了，我们公司强制用SVN...

**Comment by armink** [comment]
最新代码已经更新了，感谢反馈哈。
